### ISSUE TITLE
NODYN and Int 2F/AX=4309h

### ISSUE THREAD

**Issue by JayQ2K** [Baron-von-Riedesel/Jemm#9]
More a general question for my understanding:
Is the NODYN parameter in any way related to Int 2F/AX=4309h (http://www.ctyme.com/intr/rb-4767.htm)?

When using DOSBox-X with xms=true I need to use the NODYN switch to prevent the following message from popping up:
Warning: XMS host doesn''t provide handle array, dynamic memory allocation off!
- And doesn''t is indeed stated with 2 single quotes, so that is probably a typo.

When using any other XMM (HIMEM, HimemX) I get no error on this and can take the NODYN off.

Might be something for the README file if this is correct.

**Comment by Baron-von-Riedesel** [comment]
> Is the NODYN parameter in any way related to Int 2F/AX=4309h

An XMS memory block can only be resized if it is "unlocked", and this means its physical address may change - impossible for Jemm386 to accept, since its own code resides in this block. Therefore Jemm386 prefers to modify the xms handle array itself - something it cannot do if the above API isn't provided by the XMS host. So in this case it automatically sets the NODYN option.

The typo has already been fixed in the current (pre)release v5.80.

**Comment by JayQ2K** [comment]
Thanks for the reply. Just to be certain that I'm reading the same as you wrote though:
The EMM cannot do dynamic memory allocation if the XMM does not support Int 2F/AX=4309h?
